//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dionex.DDK.V2.ChannelTest.EditorPlugIn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dionex.DDK.V2.ChannelTest.EditorPlugIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data rate.
        /// </summary>
        internal static string Channel2D_ColFixedRate {
            get {
                return ResourceManager.GetString("Channel2D_ColFixedRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Band with.
        /// </summary>
        internal static string Channel3D_BandWidth {
            get {
                return ResourceManager.GetString("Channel3D_BandWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bunch width.
        /// </summary>
        internal static string Channel3D_BunchWidth {
            get {
                return ResourceManager.GetString("Channel3D_BunchWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. wavelength.
        /// </summary>
        internal static string Channel3D_MaxWaveLength {
            get {
                return ResourceManager.GetString("Channel3D_MaxWaveLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. wavelength.
        /// </summary>
        internal static string Channel3D_MinWaveLength {
            get {
                return ResourceManager.GetString("Channel3D_MinWaveLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref. band with.
        /// </summary>
        internal static string Channel3D_RefBandwidth {
            get {
                return ResourceManager.GetString("Channel3D_RefBandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref. wavelength.
        /// </summary>
        internal static string Channel3D_RefWaveLength {
            get {
                return ResourceManager.GetString("Channel3D_RefWaveLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Wavelength must be greater than Min. Wavelength..
        /// </summary>
        internal static string Error_Invalid3DWavelengthLimits {
            get {
                return ResourceManager.GetString("Error_Invalid3DWavelengthLimits", resourceCulture);
            }
        }
    }
}
